---
# Production environment override
services:
    php:
        env_file:
            -   docker/env/prod.env
        image: ${PHP_IMAGE:-${IMAGES_PREFIX:-}app-php-prod}:${PHP_SHA_CURRENT:-${IMAGE_TAG:-dev}}
        build:
            context: .
            target: frankenphp_prod
        ports: !override
            - name: http
              target: 80
              host_ip: ${PHP_HOST_IP:-127.0.0.1}
              published: ${PHP_HTTP_PORT:-8000}
              protocol: tcp
        secrets:
            - source: symfony_decryption_key
              target: /app/config/secrets/prod/prod.decrypt.private.php

    database:
        environment:
            POSTGRES_DB: ${DATABASE_NAME:?Missing DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER:?Missing DATABASE_USER}

    messenger:
        image: ${PHP_IMAGE:-${IMAGES_PREFIX:-}app-php-prod}:${PHP_SHA_CURRENT:-${IMAGE_TAG:-dev}}
        secrets:
            - source: symfony_decryption_key
              target: /app/config/secrets/prod/prod.decrypt.private.php
        env_file:
            - docker/env/prod.env

    scheduler:
        image: ${PHP_IMAGE:-${IMAGES_PREFIX:-}app-php-prod}:${PHP_SHA_CURRENT:-${IMAGE_TAG:-dev}}
        secrets:
            - source: symfony_decryption_key
              target: /app/config/secrets/prod/prod.decrypt.private.php
        env_file:
            - docker/env/prod.env

secrets:
    symfony_decryption_key:
        file: config/secrets/prod/prod.decrypt.private.php
