<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates Symfony Messenger's Doctrine transport table.
 *
 * The template keeps this migration versioned so async workers can start without
 * relying on Messenger's auto-setup in preprod or prod.
 */
final class Version20260903155231 extends AbstractMigration
{
    /**
     * Describes the infrastructure table created for async message delivery.
     */
    public function getDescription(): string
    {
        return 'Create the Symfony Messenger Doctrine transport table.';
    }

    /**
     * Adds the queue table and polling index expected by the Doctrine transport.
     */
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    /**
     * Removes the queue table when rolling the template migration back locally.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
