services:
    mailer:
        image: axllent/mailpit:latest

        restart: unless-stopped

        ports:
            - name: smtp
              target: 1025
              published: "1025"
              protocol: tcp
              host_ip: 127.0.0.1

            - name: web
              target: 8025
              published: "8025"
              protocol: tcp
              host_ip: 127.0.0.1
